    sudo: false
language: node_js
node_js:
  - '10'
  - '8'
before_install:
  - npm i -g npm@^10.16.0
cache:
  directories:
    - node_modules
env:
  - ESLINT_VERSION=6
before_script:
  - npm prune
notifications:
  email: false
script:
  - npm run validate
after_success:
  - npm run report-coverage && npm run semantic-release
branches:
except:
- /^v\d+\.\d+\.\d+$/
before_install:
- openssl aes-256-cbc -K $encrypted_995f46ea43c0_key -iv $encrypted_995f46ea43c0_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  
deploy:
provider: script
skip_cleanup: true
script: npm run travis-deploy && pm2 kill
on:
branch:
only:
    - greenkeeper

after_success:
npm run coveralls
